server:
  port: 8080
eureka:
  instance:
    prefIpAdress: true;
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: clientRoutes
          uri: lb://client-service
          predicates:
            - Path=/clients/**
        - id: clinicRoutes
          uri: lb://clinic-service
          predicates:
            - Path=/departments/**, /doctors/**, /facilities/**
        - id: registrationRoutes
          uri: lb://registration-service
          predicates:
            - Path=/registrations/**, /services/**
        - id: resultRoutes
          uri: lb://results-service
          predicates:
            - Path=/results/**
        - id: authServerRoutes
          uri: lb://auth-server
          predicates:
            - Path=/oauth/**
  security:
    oauth2:
      jwt-key: MjWP5L7CiDff90qA
  management:
    endpoints:
      web:
        exposure:
          include: '*'
          exclude: threaddump, heapdump
    endpoint:
      health:
        show-details: always
